services:
  simstudio:
    image: ghcr.io/simstudioai/simstudio:latest
    build:
      dockerfile: ./docker/app.Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    ports:
      - "3000:3000"
    deploy:
      resources:
        limits:
          memory: 8G
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - BETTER_AUTH_URL=${NEXT_PUBLIC_APP_URL:-http://localhost:3000}
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL:-http://localhost:3000}
      - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET:-your_auth_secret_here}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY:-your_encryption_key_here}
      - COPILOT_API_KEY=${COPILOT_API_KEY}
      - SIM_AGENT_API_URL=${SIM_AGENT_API_URL}
      - OLLAMA_URL=${OLLAMA_URL:-http://localhost:11434}
      - SOCKET_SERVER_URL=${SOCKET_SERVER_URL:-http://localhost:3002}
      - NEXT_PUBLIC_SOCKET_URL=${NEXT_PUBLIC_SOCKET_URL:-http://localhost:3002}
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - S3_LOGS_BUCKET_NAME=${S3_LOGS_BUCKET_NAME}
      - S3_KB_BUCKET_NAME=${S3_KB_BUCKET_NAME}
      - S3_EXECUTION_FILES_BUCKET_NAME=${S3_EXECUTION_FILES_BUCKET_NAME}
      - S3_CHAT_BUCKET_NAME=${S3_CHAT_BUCKET_NAME}
      - S3_COPILOT_BUCKET_NAME=${S3_COPILOT_BUCKET_NAME}
      - S3_PROFILE_PICTURES_BUCKET_NAME=${S3_PROFILE_PICTURES_BUCKET_NAME}

    depends_on:
      migrations:
        condition: service_completed_successfully
      realtime:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--spider", "--quiet", "http://127.0.0.1:3000"]
      interval: 90s
      timeout: 5s
      retries: 3
      start_period: 10s

  realtime:
    image: ghcr.io/simstudioai/realtime:latest
    restart: unless-stopped
    ports:
      - "3002:3002"
    deploy:
      resources:
        limits:
          memory: 4G
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL:-http://localhost:3000}
      - BETTER_AUTH_URL=${BETTER_AUTH_URL:-http://localhost:3000}
      - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET:-your_auth_secret_here}
    healthcheck:
      test:
        ["CMD", "wget", "--spider", "--quiet", "http://127.0.0.1:3002/health"]
      interval: 90s
      timeout: 5s
      retries: 3
      start_period: 10s

  migrations:
    image: ghcr.io/simstudioai/migrations:latest
    working_dir: /app/packages/db
    environment:
      - DATABASE_URL=${DATABASE_URL}
    command: ["bun", "run", "db:migrate"]
    restart: "no"
